<poem>    ::= <rule1> "\n" <rule2> "\n" <rule3>;
<qual>    ::= "while" | "as" | "momentarily" | "frozen";
<noun>    ::= "he" | "she" | "the shadowy figure" | "the boy" | "a child";
<tverb>   ::= "outlines" | "casts toward" | "stares at" | "captures" | "damns";
<iverb>   ::= "lingers" | "pauses" | "reflects" | "alights" | "hesitates" | "turns away" | "returns" | "kneels" | "stares";
<article> ::= "a" | "the";
<adj>     ::= "slowly" | "silently" | "darkly" | "with fear" | "expectantly" | "fearfully";
<ger>     ::= "waiting" | "pointing" | "breathing";
<onoun>   ::= "sky" | "void" | "abyss" | "star" | "darkness" | "lake" | "moon" | "cloud";
<clause>  ::= "and" " " <iverb> | "but" " "  <iverb> | "and"  " "  <iverb> | "while" " " <ger> " " <adj>;
<object>  ::= <article> " " <onoun>;
<rule1>   ::= <qual> " " <noun> " " <tverb> " " <object>;
<rule2>   ::= <noun> " " <iverb> " " <clause>;
<rule3>   ::= <qual> " " <noun> " " <iverb>;
